<a href="https://colab.research.google.com/github/nevil2006/natural-language-processing/blob/main/day_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow

In [2]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [3]:
sentences = [
    'movie was excellent',
    'movie was terrible',
    'I love this film',
    'I hate this movie',
    'best movie ever',
    'worst acting ever'
]

labels = [1,0,1,0,1,0]

In [4]:
voc_size = 5000

In [5]:
onehot_repr = [one_hot(words, voc_size) for words in sentences]

print(onehot_repr)

[[4474, 4542, 4688], [4474, 4542, 1838], [3180, 4980, 1122, 1976], [3180, 1469, 1122, 4474], [528, 4474, 3468], [3400, 81, 3468]]


In [6]:
sent_length = 5

embedded_docs = pad_sequences(
    onehot_repr,
    padding='pre',
    maxlen=sent_length
)

print(embedded_docs)

[[   0    0 4474 4542 4688]
 [   0    0 4474 4542 1838]
 [   0 3180 4980 1122 1976]
 [   0 3180 1469 1122 4474]
 [   0    0  528 4474 3468]
 [   0    0 3400   81 3468]]


In [7]:
embedding_vector_features = 10

model = Sequential()

model.add(
    Embedding(
        voc_size,
        embedding_vector_features,
        input_length=sent_length
    )
)

model.add(LSTM(100))

model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [8]:
model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [9]:
print(model.summary())

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [10]:
import numpy as np

X_final = np.array(embedded_docs)
y_final = np.array(labels)

model.fit(
    X_final,
    y_final,
    epochs=10,
    batch_size=2
)

Epoch 1/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.5000 - loss: 0.6967
Epoch 2/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5000 - loss: 0.6923
Epoch 3/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5000 - loss: 0.6927
Epoch 4/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5000 - loss: 0.6912
Epoch 5/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5000 - loss: 0.6904
Epoch 6/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5000 - loss: 0.6894
Epoch 7/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5000 - loss: 0.6888
Epoch 8/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8333 - loss: 0.6869
Epoch 9/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8333 - loss: 0.6858
Epoch 10/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8333 - loss: 0.6838


In [11]:
test_sentence = ['movie was fantastic']

test_onehot = [one_hot(words, voc_size)
               for words in test_sentence]

test_pad = pad_sequences(
    test_onehot,
    padding='pre',
    maxlen=sent_length
)

prediction = model.predict(test_pad)

print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 188ms/step
[[0.50603557]]
